// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyt_packet.proto

#ifndef PROTOBUF_cyt_5fpacket_2eproto__INCLUDED
#define PROTOBUF_cyt_5fpacket_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cyt_5fpacket_2eproto();
void protobuf_AssignDesc_cyt_5fpacket_2eproto();
void protobuf_ShutdownFile_cyt_5fpacket_2eproto();

class StruCytPacket;

// ===================================================================

class StruCytPacket : public ::google::protobuf::Message {
 public:
  StruCytPacket();
  virtual ~StruCytPacket();
  
  StruCytPacket(const StruCytPacket& from);
  
  inline StruCytPacket& operator=(const StruCytPacket& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const StruCytPacket& default_instance();
  
  void Swap(StruCytPacket* other);
  
  // implements Message ----------------------------------------------
  
  StruCytPacket* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StruCytPacket& from);
  void MergeFrom(const StruCytPacket& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string str_head = 1;
  inline bool has_str_head() const;
  inline void clear_str_head();
  static const int kStrHeadFieldNumber = 1;
  inline const ::std::string& str_head() const;
  inline void set_str_head(const ::std::string& value);
  inline void set_str_head(const char* value);
  inline void set_str_head(const char* value, size_t size);
  inline ::std::string* mutable_str_head();
  inline ::std::string* release_str_head();
  
  // required int32 room_id = 2;
  inline bool has_room_id() const;
  inline void clear_room_id();
  static const int kRoomIdFieldNumber = 2;
  inline ::google::protobuf::int32 room_id() const;
  inline void set_room_id(::google::protobuf::int32 value);
  
  // required int32 msg_len = 3;
  inline bool has_msg_len() const;
  inline void clear_msg_len();
  static const int kMsgLenFieldNumber = 3;
  inline ::google::protobuf::int32 msg_len() const;
  inline void set_msg_len(::google::protobuf::int32 value);
  
  // required int32 msg_type = 4;
  inline bool has_msg_type() const;
  inline void clear_msg_type();
  static const int kMsgTypeFieldNumber = 4;
  inline ::google::protobuf::int32 msg_type() const;
  inline void set_msg_type(::google::protobuf::int32 value);
  
  // required bytes msg_data = 5;
  inline bool has_msg_data() const;
  inline void clear_msg_data();
  static const int kMsgDataFieldNumber = 5;
  inline const ::std::string& msg_data() const;
  inline void set_msg_data(const ::std::string& value);
  inline void set_msg_data(const char* value);
  inline void set_msg_data(const void* value, size_t size);
  inline ::std::string* mutable_msg_data();
  inline ::std::string* release_msg_data();
  
  // required string str_tail = 6;
  inline bool has_str_tail() const;
  inline void clear_str_tail();
  static const int kStrTailFieldNumber = 6;
  inline const ::std::string& str_tail() const;
  inline void set_str_tail(const ::std::string& value);
  inline void set_str_tail(const char* value);
  inline void set_str_tail(const char* value, size_t size);
  inline ::std::string* mutable_str_tail();
  inline ::std::string* release_str_tail();
  
  // @@protoc_insertion_point(class_scope:StruCytPacket)
 private:
  inline void set_has_str_head();
  inline void clear_has_str_head();
  inline void set_has_room_id();
  inline void clear_has_room_id();
  inline void set_has_msg_len();
  inline void clear_has_msg_len();
  inline void set_has_msg_type();
  inline void clear_has_msg_type();
  inline void set_has_msg_data();
  inline void clear_has_msg_data();
  inline void set_has_str_tail();
  inline void clear_has_str_tail();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* str_head_;
  ::google::protobuf::int32 room_id_;
  ::google::protobuf::int32 msg_len_;
  ::std::string* msg_data_;
  ::std::string* str_tail_;
  ::google::protobuf::int32 msg_type_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_cyt_5fpacket_2eproto();
  friend void protobuf_AssignDesc_cyt_5fpacket_2eproto();
  friend void protobuf_ShutdownFile_cyt_5fpacket_2eproto();
  
  void InitAsDefaultInstance();
  static StruCytPacket* default_instance_;
};
// ===================================================================


// ===================================================================

// StruCytPacket

// required string str_head = 1;
inline bool StruCytPacket::has_str_head() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StruCytPacket::set_has_str_head() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StruCytPacket::clear_has_str_head() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StruCytPacket::clear_str_head() {
  if (str_head_ != &::google::protobuf::internal::kEmptyString) {
    str_head_->clear();
  }
  clear_has_str_head();
}
inline const ::std::string& StruCytPacket::str_head() const {
  return *str_head_;
}
inline void StruCytPacket::set_str_head(const ::std::string& value) {
  set_has_str_head();
  if (str_head_ == &::google::protobuf::internal::kEmptyString) {
    str_head_ = new ::std::string;
  }
  str_head_->assign(value);
}
inline void StruCytPacket::set_str_head(const char* value) {
  set_has_str_head();
  if (str_head_ == &::google::protobuf::internal::kEmptyString) {
    str_head_ = new ::std::string;
  }
  str_head_->assign(value);
}
inline void StruCytPacket::set_str_head(const char* value, size_t size) {
  set_has_str_head();
  if (str_head_ == &::google::protobuf::internal::kEmptyString) {
    str_head_ = new ::std::string;
  }
  str_head_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StruCytPacket::mutable_str_head() {
  set_has_str_head();
  if (str_head_ == &::google::protobuf::internal::kEmptyString) {
    str_head_ = new ::std::string;
  }
  return str_head_;
}
inline ::std::string* StruCytPacket::release_str_head() {
  clear_has_str_head();
  if (str_head_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_head_;
    str_head_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 room_id = 2;
inline bool StruCytPacket::has_room_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StruCytPacket::set_has_room_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StruCytPacket::clear_has_room_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StruCytPacket::clear_room_id() {
  room_id_ = 0;
  clear_has_room_id();
}
inline ::google::protobuf::int32 StruCytPacket::room_id() const {
  return room_id_;
}
inline void StruCytPacket::set_room_id(::google::protobuf::int32 value) {
  set_has_room_id();
  room_id_ = value;
}

// required int32 msg_len = 3;
inline bool StruCytPacket::has_msg_len() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StruCytPacket::set_has_msg_len() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StruCytPacket::clear_has_msg_len() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StruCytPacket::clear_msg_len() {
  msg_len_ = 0;
  clear_has_msg_len();
}
inline ::google::protobuf::int32 StruCytPacket::msg_len() const {
  return msg_len_;
}
inline void StruCytPacket::set_msg_len(::google::protobuf::int32 value) {
  set_has_msg_len();
  msg_len_ = value;
}

// required int32 msg_type = 4;
inline bool StruCytPacket::has_msg_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StruCytPacket::set_has_msg_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StruCytPacket::clear_has_msg_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StruCytPacket::clear_msg_type() {
  msg_type_ = 0;
  clear_has_msg_type();
}
inline ::google::protobuf::int32 StruCytPacket::msg_type() const {
  return msg_type_;
}
inline void StruCytPacket::set_msg_type(::google::protobuf::int32 value) {
  set_has_msg_type();
  msg_type_ = value;
}

// required bytes msg_data = 5;
inline bool StruCytPacket::has_msg_data() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void StruCytPacket::set_has_msg_data() {
  _has_bits_[0] |= 0x00000010u;
}
inline void StruCytPacket::clear_has_msg_data() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void StruCytPacket::clear_msg_data() {
  if (msg_data_ != &::google::protobuf::internal::kEmptyString) {
    msg_data_->clear();
  }
  clear_has_msg_data();
}
inline const ::std::string& StruCytPacket::msg_data() const {
  return *msg_data_;
}
inline void StruCytPacket::set_msg_data(const ::std::string& value) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::kEmptyString) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(value);
}
inline void StruCytPacket::set_msg_data(const char* value) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::kEmptyString) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(value);
}
inline void StruCytPacket::set_msg_data(const void* value, size_t size) {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::kEmptyString) {
    msg_data_ = new ::std::string;
  }
  msg_data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StruCytPacket::mutable_msg_data() {
  set_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::kEmptyString) {
    msg_data_ = new ::std::string;
  }
  return msg_data_;
}
inline ::std::string* StruCytPacket::release_msg_data() {
  clear_has_msg_data();
  if (msg_data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msg_data_;
    msg_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string str_tail = 6;
inline bool StruCytPacket::has_str_tail() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void StruCytPacket::set_has_str_tail() {
  _has_bits_[0] |= 0x00000020u;
}
inline void StruCytPacket::clear_has_str_tail() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void StruCytPacket::clear_str_tail() {
  if (str_tail_ != &::google::protobuf::internal::kEmptyString) {
    str_tail_->clear();
  }
  clear_has_str_tail();
}
inline const ::std::string& StruCytPacket::str_tail() const {
  return *str_tail_;
}
inline void StruCytPacket::set_str_tail(const ::std::string& value) {
  set_has_str_tail();
  if (str_tail_ == &::google::protobuf::internal::kEmptyString) {
    str_tail_ = new ::std::string;
  }
  str_tail_->assign(value);
}
inline void StruCytPacket::set_str_tail(const char* value) {
  set_has_str_tail();
  if (str_tail_ == &::google::protobuf::internal::kEmptyString) {
    str_tail_ = new ::std::string;
  }
  str_tail_->assign(value);
}
inline void StruCytPacket::set_str_tail(const char* value, size_t size) {
  set_has_str_tail();
  if (str_tail_ == &::google::protobuf::internal::kEmptyString) {
    str_tail_ = new ::std::string;
  }
  str_tail_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StruCytPacket::mutable_str_tail() {
  set_has_str_tail();
  if (str_tail_ == &::google::protobuf::internal::kEmptyString) {
    str_tail_ = new ::std::string;
  }
  return str_tail_;
}
inline ::std::string* StruCytPacket::release_str_tail() {
  clear_has_str_tail();
  if (str_tail_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_tail_;
    str_tail_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cyt_5fpacket_2eproto__INCLUDED
